# Generated by Django 4.2.2 on 2023-06-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('voteSum', models.IntegerField(default=0)),
                ('cont', models.IntegerField(default=0)),
            ],
        ),
    ]
